language: go
install: go get -v github.com/spf13/hugo

script:
- hugo build

after_success:
- git config user.name "Travis CI"
- git config user.email "dev@md2k.org"
- git remote add gh-token "https://${GH_TOKEN}@github.com/MD2Korg/software.md2k.org.git";
- git fetch gh-token
- git checkout gh-token/dev
- mkdocs gh-deploy -v --clean --remote-name gh-token -b master -m "Travis CI deployed
  to master with build $TRAVIS_BUILD_NUMBER"
