language: go
install: go get -v github.com/spf13/hugo
script:
- git clone https://github.com/devcows/hugo-universal-theme themes/hugo-universal-theme
- hugo build
after_success:
- git config user.name "Travis CI"
- git config user.email "dev@md2k.org"
- sh ./_scripts/publish_toghpages.sh
- eval `ssh-agent -s`
- ssh-add id_rsa_software.md2k.org
- git push origin gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_c79eb7350bf3_key -iv $encrypted_c79eb7350bf3_iv -in id_rsa_software.md2k.org.enc -out id_rsa_software.md2k.org -d
